services:
        - mongodb
language: node_js
node_js:
        - "11"
script:
        - npm run lint
        - npm test
        - npm run test-integration
        - npm run test-integration-external
        - cd ./bin/watcher/ethereum/ && npm install && ls ./node_modules/ && ls -R ./node_modules/adex-protocol-eth/ && ./test/run.sh

