services:
        - mongodb
        - redis
language: node_js
node_js:
        - "10"
script:
        - npm run lint
        - npm test
        - npm run test-adapter
        - npm run test-integration
        #- npm run test-integration-external
