version: "3"
services:
  leader:
    container_name: adex_leader
    restart: always
    build: .
    ports: 
      - "8005:8005"
    links: 
      - mongo
  follower:
    container_name: adex_follower
    restart: always
    build: .
    ports: 
      - "8006:8006"
    links: 
      - mongo
    environment: 
      - PORT=8006
      - IDENTITY=awesomeFollower
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"

